POST http://localhost:3003/api/blogs/ 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlY29kZWRUb2tlbiIsImlkIjoiNWZhNTM1YmMwNTliNDcxMzI0YjZjMWZiIiwiaWF0IjoxNjA0NjYzMDQ5fQ.fsnOMTjjToeTBmoKOy6h9yt1XE32z8q17CQ4KS1xfIQ

{
"url": "www.decodedtoken.com", 
"title": "decoded works",
"author": "R.F",
"likes": "200"
}